-- AlterEnum
-- Adding specific fixed income asset types to AssetType enum
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'CDB';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'RDB';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'LCI';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'LCA';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'TESOURO';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'POUPANCA';
